jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: "{{env_var('AIRFLOW_POSTGRES_USER')}}"
      password: "{{env_var('AIRFLOW_POSTGRES_PASSWORD')}}"
      port: 5432
      dbname: postgres
      schema: mart
      threads: 6
    dev_fusion:
      type: snowflake
      account: lwlungs-ug60909
      user: Adhil
      password: "Adhil@ecloudcontrol123"
      role: ACCOUNTADMIN
      database: JAFFLE_DB
      warehouse: COMPUTE_WH
      schema: FUSION_MART
      threads: 6
  
